package com.harismexis.rates.model

data class Rates(
    var AUD: Float?,
    var BGN: Float?,
    var BRL: Float?,
    var CAD: Float?,
    var CHF: Float?,
    var CNY: Float?,
    var CZK: Float?,
    var DKK: Float?,
    var EUR: Float?,
    var GBP: Float?,
    var HKD: Float?,
    var HRK: Float?,
    var HUF: Float?,
    var IDR: Float?,
    var ILS: Float?,
    var INR: Float?,
    var ISK: Float?,
    var JPY: Float?,
    var KRW: Float?,
    var MXN: Float?,
    var MYR: Float?,
    var NOK: Float?,
    var NZD: Float?,
    var PHP: Float?,
    var PLN: Float?,
    var RON: Float?,
    var RUB: Float?,
    var SEK: Float?,
    var SGD: Float?,
    var THB: Float?,
    var USD: Float?,
    var ZAR: Float?
)